@startuml

actor 当前用户 as userA #white
participant 当前用户移动端 as clientA #white
participant 用户服务 as biz #white
participant MySql as db #white
participant Neo4j as gb #white
participant 消息服务 as msg #white
participant 目标用户移动端 as clientB #white
actor 目标用户 as userB #white

activate userA
activate clientA
activate biz
activate db
activate gb
activate msg
activate clientB
activate userB

userA -> clientA: 点击关注按钮
clientA -> biz: 发起关注请求
biz -> gb: 检查是否存在好友关系
biz -> db: 自己关注数+1，对方粉丝数+1\n对方关注自己则双方好友数+1
biz -> gb: 创建关注关系
biz -> clientA: 关注成功
clientA -> userA: 关注列表刷新
biz -> msg: 发送被关注消息
msg -> clientB: 消息推送
clientB -> userB: 被关注提醒

deactivate userB
deactivate clientB
deactivate msg
deactivate gb
deactivate db
deactivate biz
deactivate clientA
deactivate userA

@enduml